- name: Stop firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Restart Apache
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: Restart OpenLDAP Server
  service:
    name: slapd
    state: restarted
